export const datingProfiles = [
  {
    source: require("../assets/DatingProfiles/Profile1.png"),
    id: 1,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
  },
  {
    id: 2,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile2.png"),
  },
  {
    id: 3,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile3.png"),
  },
  {
    id: 4,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile4.png"),
  },
  {
    id: 5,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile1.png"),
  },
];
