export const datingProfiles = [
  {
    source: require("../assets/DatingProfiles/Profile1.png"),
    bookmark: require("../assets/DatingProfiles/Profile1Bookmark.png"),
    id: 0,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
  },
  {
    id: 1,
    name: "Lauras Clint",
    age: 29,
    location: "California, UK",
    gender: "female",
    height: "6'0",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 90,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile2.png"),
    bookmark: require("../assets/DatingProfiles/Profile2Bookmark.png"),
  },
  {
    id: 2,
    name: "Henna Clint",
    age: 20,
    location: "Paris, Tokyo",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 84,
    liked: true,
    matchImg: require("../assets/DatingProfiles/Profile2Bookmark.png"),
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile3.png"),
    bookmark: require("../assets/DatingProfiles/Profile3Bookmark.png"),
  },
  {
    id: 3,
    name: "Dannie Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'9",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 65,
    liked: true,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile4.png"),
    bookmark: require("../assets/DatingProfiles/Profile4Bookmark.png"),
  },
  {
    id: 4,
    name: "Henna Clint",
    age: 22,
    location: "London, UK",
    gender: "female",
    height: "5'4",
    education: "Bachelors in Computer Science",
    job: "Software Engineer",
    ethinity: "South Asian",
    matchPercentage: 92,
    liked: false,
    bio: "Looking for a reason to delete this app, and hopefully, you’re it!",
    source: require("../assets/DatingProfiles/Profile1.png"),
    bookmark: require("../assets/DatingProfiles/Profile1Bookmark.png"),
  },
];
